node {
    def commit_id
    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
    }  
    stage('Deploying logging using elkStack') {  
        sh"""
            cd docker-elk
            docker-compose build && docker-compose up -d
        """
        }
    }

